# Generated by Django 6.0.1 on 2026-03-17 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("item_id", models.UUIDField(blank=True, null=True)),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=256)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("direction", models.CharField(blank=True, max_length=50, null=True)),
                ("current_stock", models.IntegerField(blank=True, null=True)),
                (
                    "performed_by_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventory",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
