# Generated by Django 6.0.1 on 2026-03-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="low_stock_notification",
            field=models.BooleanField(default=False),
        ),
    ]
