# Generated by Django 6.0.1 on 2026-03-29 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores custom field values as a dictionary: {'field_id': 'value'}",
            ),
        ),
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=256)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("direction", models.CharField(blank=True, max_length=50, null=True)),
                ("current_stock", models.IntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="InventoryCustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("text", "Text"), ("number", "Number")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="inventory.inventory",
                    ),
                ),
            ],
            options={
                "unique_together": {("inventory", "name")},
            },
        ),
    ]
