# Generated by Django 6.0.1 on 2026-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stocklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklog",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
