# Generated by Django 6.0.1 on 2026-04-08 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stocklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores custom field values as a dictionary: {'field_id': 'value'}",
            ),
        ),
        migrations.CreateModel(
            name="InventoryCustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("text", "Text"), ("number", "Number")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="inventory.inventory",
                    ),
                ),
            ],
            options={
                "unique_together": {("inventory", "name")},
            },
        ),
    ]
