# Generated by Django 6.0.1 on 2026-04-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_image"),
        ("inventory", "0003_stocklog"),
    ]

    operations = []
