# Generated by Django 6.0.1 on 2026-04-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_low_stock_notification"),
        ("inventory", "0003_stocklog"),
    ]

    operations = []
