# Generated by Django 6.0.1 on 2026-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_merge_20260409_0705"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
