# Generated by Django 6.0.1 on 2026-04-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventoryitem_custom_fields_inventorycustomfield"),
        ("inventory", "0005_inventoryitem_description"),
    ]

    operations = []
