[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.12.0",
    "psycopg>=3.3.2",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
explicit_package_bases = true

[tool.django-stubs]
django_settings_module = "config.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py", "*_test.py"]
addopts = "--reuse-db"

[tool.ruff]
line-length = 80
target-version = "py312"
extend-exclude = [
    "*/migrations/*",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "B",
    "S",
    "A",
    "C4",
    "UP",
    "SIM",
    "RUF",
    "I",
]
ignore = []

[tool.ruff.lint.per-file-ignores]
# Tests intentionally use `assert` (S101) and dummy passwords (S105)(S106).
"**/tests/**/*.py" = ["S101", "S105", "S106"]

# Ignore "Standard pseudo-random generators" in the seed script
"**/management/commands/seed_db.py" = ["S311"]

[dependency-groups]
dev = [
    "django-stubs>=5.2.8",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-django>=4.11.1",
    "ruff>=0.9.0",
]
