[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.12.0",
    "djangorestframework>=3.16.1",
    "drf-spectacular>=0.29.0",
    "psycopg>=3.3.2",
    "adrf>=0.1.0",
    "gunicorn",
    "pillow>=11.3.0",
    "requests>=2.33.1",
    "redis",
    "django-redis",
]

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
allow_redefinition = true
explicit_package_bases = true
exclude = ["migrations/"]

[tool.pylsp-mypy]
enabled = true
live_mode = false
dmypy = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py", "*_test.py"]
addopts = "--reuse-db"

[tool.ruff]
line-length = 80
target-version = "py312"
extend-exclude = [
    "*/migrations/*",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "B",
    "S",
    "A",
    "C4",
    "UP",
    "SIM",
    "RUF",
    "I",
]
ignore = []

[tool.ruff.lint.per-file-ignores]
# Tests intentionally use `assert` (S101) and dummy passwords (S105)(S106)(S107)
"**/tests/**/*.py" = ["S101", "S105", "S106", "S107"]

# Ignore "Standard pseudo-random generators" in the seed scripts
"**/management/commands/*.py" = ["S311"]

[dependency-groups]
dev = [
    "debugpy>=1.8.19",
    "django-types>=0.22.0",
    "djangorestframework-types>=0.9.0",
    "mypy>=1.19.1",
    "pylsp-mypy>=0.7.0",
    "pytest>=9.0.2",
    "pytest-django>=4.11.1",
    "python-lsp-server>=1.14.0",
    "ruff>=0.9.0",
    "types-requests>=2.33.0.20260408",
]
